### ISSUE TITLE
color change 

### ISSUE THREAD

**Issue by Carinazhao22** [jzhangbs/Vis-MVSNet#14]
Hello,

The color of the model is wrong after running on dtu test data. The left side is the correct color but the actual output is the right side. How can I fix it? Thanks
![image](https://user-images.githubusercontent.com/52422263/109590101-3a93b400-7ac0-11eb-9743-f787336708d8.png)

**Comment by jzhangbs** [comment]
because opencv load color as BGR instead of RGB. you can reverse the dimension 1 of `c_all` at https://github.com/jzhangbs/Vis-MVSNet/blob/master/fusion.py#L157

**Comment by Carinazhao22** [comment]
Thanks, it works.
