### ISSUE TITLE
T&T dataset test error

### ISSUE THREAD

**Issue by DingYikang** [jzhangbs/Vis-MVSNet#17]
Hi, I'm trying to test the advanced sequence data of tnt dataset, but when I run sh sh/tnt.sh, I got "TypeError: forward() missing 3 required positional arguments: 'sample', 'depth_nums', and 'interval_scales'", I checked the code but found nothing missing. I don't know what happend, could you help this? Thank you!

**Comment by xhangHU** [comment]
Have you solved this problem? I also encountered the same problem

**Comment by mili130422** [comment]
Have you solved this problem? I also encountered the same problem

**Comment by jzhangbs** [comment]
Hi @mili130422, are you using a machine with multiple GPUs? If yes, you need to set visible GPUs.
