### ISSUE TITLE
Release DTU dataset

### ISSUE THREAD

**Issue by DingYikang** [jzhangbs/Vis-MVSNet#18]
Hi, I'm wondering when will you release the pre-processed DTU dataset, thank you!

**Comment by jzhangbs** [comment]
Hi Yikang, it has been released in c35d8c6c73a6c3e0646866818e699a0856511fa3

**Comment by DingYikang** [comment]
> Hi Yikang, it has been released in [c35d8c6](https://github.com/jzhangbs/Vis-MVSNet/commit/c35d8c6c73a6c3e0646866818e699a0856511fa3)

It's very kind of you~ Thanks a lot!
