### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by decai-chen** [jzhangbs/Vis-MVSNet#2]
Hello, 

Is it possible for you to provide pre-trained model, for quick testing or further fine-tuning?

Thank you!

**Comment by jzhangbs** [comment]
I have uploaded the pretrained model in the latest commit. Please see pretrained model dir.

**Comment by decai-chen** [comment]
> I have uploaded the pretrained model in the latest commit. Please see pretrained model dir.

Thank you for your kind and fast reply!
