### ISSUE TITLE
There was a problem during the test

### ISSUE THREAD

**Issue by xhangHU** [jzhangbs/Vis-MVSNet#26]
When I ran the test, he was stuck at this step and there was no change for two days.

Number of model parameters: 1162696
load pretrained_model/vis/-1
  0%|                                                                                                                     | 0/98 [00:00<?, ?it/s]

**Comment by jzhangbs** [comment]
Hi, could you please check where the code stucked by adding some debugging output?

**Comment by xhangHU** [comment]
After debugging, I found that it runs to 96 lines
  with torch.no_grad():
The code after that did not run

**Comment by xhangHU** [comment]
I think it’s stuck on  98 and 99 line

outputs, refined_depth, prob_maps = model(sample, cas_depth_num, cas_interv_scale, mode=args[[est_depth_1, pair_results_1], [est_depth_2, pair_results_2], [est_depth_3, pair_results]] = outputs

**Comment by xhangHU** [comment]
Finally I determined the location of the problem
Is line 27 of model_cas.py
         out = self.init_conv(x)
I am stuck at this step using my own data and the provided data set. How can I solve this problem?

**Comment by xhangHU** [comment]
I solved this problem. The reason is that multiple GPUs are used. When I use
OMP_NUM_THREADS=1 MKL_NUM_THREADS=1
Solved the problem after restricting threads
