### ISSUE TITLE
点云融合效果很差

### ISSUE THREAD

**Issue by aweijx** [jzhangbs/Vis-MVSNet#3]
谢谢你的开源 @jzhangbs ，想问下为什么我用fusion.py融合的点云效果很差，有哪些参数需要改动吗
![2020-10-27 22-22-08屏幕截图](https://user-images.githubusercontent.com/49384093/97315050-4289e000-18a3-11eb-927b-dd31424cd80c.png)

**Comment by jzhangbs** [comment]
噪点多的话试试调一下prob threshold和number of consistent views
