### ISSUE TITLE
pretrained model tank and temple dataset

### ISSUE THREAD

**Issue by l1346792580123** [jzhangbs/Vis-MVSNet#34]
I have found that the provided model does not perform well on the tank and temple dataset. Could you please provide the pretrained model on tank and temple dataset?

**Comment by jzhangbs** [comment]
Hi, thanks for the interest. The provided model is exactly the one we used for benchmarking. And the community usually does not fine-tune the model on TnT dataset. They are either trained on DTU, BlendedMVS or other datasets.

**Comment by l1346792580123** [comment]
Thanks for your reply.
