### ISSUE TITLE
About the camera intrinsics in Tank and Template

### ISSUE THREAD

**Issue by zhao-yiqun** [jzhangbs/Vis-MVSNet#37]
Hi

Thanks for your work and code releasing.

I checked your preprocessed tank and template dataset with known cameras like follows:

 extrinsic
0.999749 0.0222156 -0.00306238 0.0954387
-0.0223105 0.999119 -0.0355459 -0.0991731
0.00227 0.0356053 0.999363 1.04493
0.0 0.0 0.0 1.0

intrinsic
1162.86 0 963.831
0 1162.86 541.647
0 0 1

0.367867 0.00391897 730 3.22871

I understand the extrinsic and intrisic means. But I wonder what's the meaning of the last lines. I checked the code, However still don't know what does it mean.

Thanks.

**Comment by jzhangbs** [comment]
Hi @zhao-yiqun, they describe the depth range for this view. They are `depth start, depth interval, depth numbers, depth end` respectively.

Note that we will adjust the depth number by cmd args. We will keep the start and the end, and set the depth interval accordingly. And in coarse-to-fine structure, the actual depth number and interval are scaled based on this default depth grids.

**Comment by zhao-yiqun** [comment]
Thanks for your kindly reply. Now I understand it.

Bests.
