### ISSUE TITLE
Fail to extract the pretrained model 20000.tar

### ISSUE THREAD

**Issue by mazeyu** [jzhangbs/Vis-MVSNet#4]
Why do I fail to extract the pretrained model 20000.tar? Thanks

**Comment by XYZ-qiyh** [comment]
I met the same problem. Could you please upload the uncompressed model weights? @jzhangbs 
![image](https://user-images.githubusercontent.com/45621782/100684500-6ade9000-33b5-11eb-97ea-6cff832b951b.png)

**Comment by jzhangbs** [comment]
You don't need to extract it. It's my mistake to consider that pytorch will save the model as a tarball. You can use the pretrained model by --load_path ./pretrained_model/vis

**Comment by mazeyu** [comment]
Thanks. It works.
