### ISSUE TITLE
Depth Scale Consistency

### ISSUE THREAD

**Issue by gitouni** [jzhangbs/Vis-MVSNet#40]
Thanks for sharing this work. No Bugs to report here, but I have a question about depth scale consistency. 

Suppose that the model predicts the depth map of `frame 0` and `frame 1` as `depth 0` and `depth 1`. Are `depth 0` and `depth 1` consistent with each other in the global map?

In a simple case, imaging that there is only one plane vertical to the principle axis in the scene and the relative motion between `frame 0` and `frame 1` is `[0,0,-1]` (forward 1 m). If the max_depth in `depth 0` is 25,  the max_depth of `depth 1` must be 24, right?

Appreciate your reply.

**Comment by jzhangbs** [comment]
Yes if all the depth values are estimated correctly. Actually one of the post filtering criteria is to check whether the estimated depths are multiview consistent. 

BTW the simple case you mentioned is difficult for mvs. Normally we don't consider moving forward cases.

**Comment by gitouni** [comment]
Thanks for your reply. I agree that moving foward cases are dfficult for MVS currently, I tried Vis-MVSNet on KITTI datasets. The results are acceptable but not as good as those on DTU or Temple and Tanks.
![0_flow3_depth](https://github.com/jzhangbs/Vis-MVSNet/assets/30369762/fe2a7cfc-74c1-44ec-816d-e0033c82cb8d)
![0_flow3_prob](https://github.com/jzhangbs/Vis-MVSNet/assets/30369762/896abe3a-207c-4089-898d-343a2681459c)
![00000000](https://github.com/jzhangbs/Vis-MVSNet/assets/30369762/ea56feae-e229-47d0-833a-3f59ca646139)
