### ISSUE TITLE
About DTU dataset publication

### ISSUE THREAD

**Issue by t2kasa** [jzhangbs/Vis-MVSNet#5]
Hi, thank you for the nice work and sharing code!

I would like to try training and testing on DTU dataset.
Is there a timeline for the publication of the dataset?

**Comment by jzhangbs** [comment]
You can use the preprocessed DTU dataset provided by MVSNet. Although it's in low resolution, it should be enough for training and validation. For testing, you can use the images from the official website and evaluate the point cloud.

**Comment by t2kasa** [comment]
Thanks, I will try it!
